## Домашнее задани е к уроку 5


### 1. Найдите посредством NumPy SVD для матрицы:

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1, 2, 0],[0, 0, 5],[3,-4,2],[1,6,5], [0,1,0]])
print(f'Matrix A: \n{A}')

Matrix A: 
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))]=s

In [4]:
print(D)                                # диагональная матрица

[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(U)

[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [6]:
print(np.dot(U.T, U))                 # матрица U ортогональная

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1. -0. -0.]
 [ 0. -0. -0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [7]:
print(V)

[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [8]:
print(np.dot(V.T, V))                  # матрица V ортогональная

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
print(np.dot(np.dot(U,D),V.T))         # проверка

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


### 2. Для матрицы из предыдущего задания найдите:

### а) евклидову норму

In [10]:
from numpy.linalg import norm
print(norm(A, ord=2))

8.824868854820442


### б) норму Фробениуса

In [11]:
print(norm(A, ord='fro'))

11.045361017187261
